language: java

services:
  - docker

#before_install:

#install:

#before_script:
  
# Run XSLT
script:
  - docker run -v ./:/data merijntjetak/latex-moderncv example.tex
   

#after_success:
#  - if [ "$TRAVIS_BRANCH" == "master" ]; then
#    docker build -t mwolfram/cv . ;
#    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
#    docker push mwolfram/cv;
#    fi
