language: java

services:
  - docker

#before_install:

#install:

#before_script:
  
# Run converter
script:
  # - docker run -v $TRAVIS_BUILD_DIR:/data merijntjetak/latex-moderncv example.tex
  # - docker run -v $TRAVIS_BUILD_DIR:/opt/resume gabrielruiu/json-resume
  - docker run -v $TRAVIS_BUILD_DIR:/home/ latrokles/json-resume:latest example.json
   

#after_success:
#  - if [ "$TRAVIS_BRANCH" == "master" ]; then
#    docker build -t mwolfram/cv . ;
#    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
#    docker push mwolfram/cv;
#    fi
